
# Travis.ci file https://docs.travis-ci.com/user/tutorial/
# Continuous integration

# Login to https://travis-ci.com/ using your github credentials
# Add this repository to travis
# Every time there is a commit, this script will be run and result emailed

language: cpp

dist: xenial

before_install:
  - uname -a
  - clang-tidy --version


script:
    - chmod 755 simplecompile.sh
    - ./simplecompile.sh
    - echo "Travis is done!"
